version: '3.9'

services:
  mongodb:
    image: mongo:4.4.14
    # command: mongod --auth
    ports:
      - 27017:27017
    volumes:
      - ./docker/mongo:/data/db
    environment:
      # - MONGO_INITDB_DATABASE=db
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
